config/routes.rb
Rails.application.routes.draw do
  get 'builds/show'

  get 'builds/new'

  root "welcome#index"

  resources :projects, only: [:new, :create, :show] do
    resources :topics, only: [:show, :new, :create] do
      resources :builds, only: [:show, :new, :create] do
        get 'plist' => "builds#plist"
      end
    end

    post 'hooks/github' => 'projects/hooks#github'
  end

  namespace :api do
    resources :projects, only: [] do
      resources :builds, only: :create
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/build.rb
class Build < ApplicationRecord
  belongs_to :topic, touch: true

  validates :name, presence: true

  validates :bundle_identifier, presence: true
  validates :bundle_version, presence: true
  validates :url, presence: true
end

app/models/github_hook.rb
class GithubHook
  attr_reader :project, :request

  def initialize(project:, request:)
    @project = project
    @request = request
  end

  def event_type
    request.env["HTTP_X_GITHUB_EVENT"].to_sym
  end

  def body
    @body ||= JSON.parse(request.raw_post, symbolize_names: true)
  end

  def repository_name
    body[:repository][:full_name]
  end

  def number
    body[:number]
  end

  def request_url
    @request_url ||= URI.parse(request.url)
  end

  def run!
    case event_type
    when :pull_request
      make_topic_from_request do |new_topic|
        notify_topic_created(new_topic) if project.has_github_access?
      end
    end
  end

  def make_topic_from_request
    url = body[:pull_request][:html_url]
    name = body[:pull_request][:title]

    topic = project.topics.find_or_initialize_by(url: url)
    topic.name = name

    topic_inserted = topic.new_record?

    topic.save!

    yield(topic) if topic_inserted && block_given?
  end

  def notify_topic_created(topic)
    topic_url = Rails.application.routes.url_helpers.project_topic_url(project.guid, topic.id, host: request_url.host, port: request_url.port, protocol: request_url.scheme)
    client.add_comment(repository_name, number, <<COMMENT)
Over-the-air installation will be available from #{topic_url}.
COMMENT
  end

  def client
    if project.has_github_access?
      @client ||= Octokit::Client.new(access_token: project.gh_access_token)
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  self.primary_key = :guid

  has_many :topics, foreign_key: :project_guid, dependent: :destroy

  validates :name, presence: true

  before_save :ensure_guid
  after_save :ensure_default_topic

  def ensure_guid
    self.guid = SecureRandom.uuid if guid.blank?
  end

  def ensure_default_topic
    if topics.empty?
      topics.create!(name: nil, url: nil)
    end
  end

  def has_github_access?
    gh_access_token.present?
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :project, foreign_key: :project_guid
  has_many :builds, dependent: :destroy

  scope :master, -> { where(name: nil) }
end

app/controllers/api/builds_controller.rb
class Api::BuildsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :reject_if_not_json_request

  J = StrongJSON.new do
    let :build, object(name: string, url: string, bundle_version: string, bundle_identifier: string)
    let :build_request, object(topic_url: string?, build: build)
  end

  def create(project_id)
    project = Project.find(project_id)

    json = posted_json(as: J.build_request)

    topic_url = json[:topic_url]
    build_attributes = json[:build]

    if topic_url
      topic = project.topics.find_or_create_by!(url: topic_url) do |topic|
        topic.name = topic_url
      end
    else
      topic = project.topics.where(name: nil, url: nil).first
    end

    build = topic.builds.create!(build_attributes)

    render status: :ok, json: { build_url: project_topic_build_url(project.guid, topic.id, build.id) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def posted_json(as: )
    as.coerce(JSON.parse(request.raw_post, symbolize_names: true))
  end

  def reject_if_not_json_request
    unless request.format.json?
      render status: 400, json: ["Send me request as JSON"]
    end
  end
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  def show(project_id, topic_id, id)
    @project = Project.find(project_id)
    @topic = @project.topics.find(topic_id)
    @build = @topic.builds.find(id)
  end

  def new(project_id, topic_id)
    @project = Project.find(project_id)
    @topic = @project.topics.find(topic_id)
    @build = @topic.builds.new
  end

  def create(project_id, topic_id, build)
    @project = Project.find(project_id)
    @topic = @project.topics.find(topic_id)
    @build = @topic.builds.new(build.permit(:url, :bundle_version, :bundle_identifier, :name))

    if @build.save
      redirect_to project_topic_build_url(@project.guid, @topic.id, @build.id)
    else
      render :new
    end
  end

  def plist(project_id, topic_id, build_id)
    @project = Project.find(project_id)
    @topic = @project.topics.find(topic_id)
    @build = @topic.builds.find(build_id)
  end
end

app/controllers/projects/hooks_controller.rb
class Projects::HooksController < ApplicationController
  skip_before_action :verify_authenticity_token

  def github(project_id)
    project = Project.find(project_id)

    ApplicationRecord.transaction do
      hook = GithubHook.new(project: project, request: request)
      hook.run!
    end

    render status: :ok, json: []
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def create(project)
    @project = Project.new(project.permit(:name, :gh_access_token))
    if @project.save
      redirect_to project_url(@project.guid)
    else
      render :new
    end
  end

  def new
    @project = Project.new
  end

  def show(id)
    @project = Project.find(id)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def show(project_id, id)
    @project = Project.find(project_id)
    @topic = @project.topics.find(id)
  end

  def new(project_id)
    @project = Project.find(project_id)
    @topic = @project.topics.new
  end

  def create(project_id, topic)
    @project = Project.find(project_id)
    @topic = @project.topics.new(topic.permit(:name, :url))

    if @topic.save
      redirect_to project_topic_url(@project.guid, @topic.id)
    else
      render :new
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def request_from_ios_device?
    request.env["HTTP_USER_AGENT"].try do |ua|
      ua =~ /iPhone/ || ua =~ /iPad/ || ua =~ /iPod/
    end
  end
end

app/helpers/builds_helper.rb
module BuildsHelper
  def install_plist_url(build)
    params = {
      action: "download-manifest",
      url: project_topic_build_plist_url(build.topic.project.guid, build.topic.id, build.id)
    }
    "itms-services://?#{params.to_query}"
  end
end

app/helpers/projects/hooks_helper.rb
module Projects::HooksHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
  def topic_name(topic)
    topic.name || I18n.t('models.topic.default_name')
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/builds/new.html.haml
%h1
  New Build
  %small on #{topic_name(@topic)} / #{@project.name}

= form_for @build, url: project_topic_builds_url(@project.guid, @topic.id) do |t|
  .form-group
    = t.label :name
    = t.text_field :name, class: "form-control"
  .form-group
    = t.label :bundle_identifier
    = t.text_field :bundle_identifier, class: "form-control"
  .form-group
    = t.label :bundle_version
    = t.text_field :bundle_version, class: "form-control"
  .form-group
    = t.label :url
    = t.text_field :url, class: "form-control"
  = t.submit class: "btn btn-default"

app/views/builds/show.html.haml
- content_for :breadcrumb do
  %li= link_to @project.name, project_url(@project.guid)
  %li= link_to topic_name(@topic), project_topic_url(@project.guid, @topic.id)
  %li.active Build

%h1
  Build on #{topic_name(@topic)}
  %small on #{@project.name}

%dl
  %dt Created at
  %dd= local_time @build.created_at
  %dt Bundle Identifier
  %dd= @build.bundle_identifier
  %dt Bundle Version
  %dd= @build.bundle_version
  %dt URL
  %dd= @build.url

- if request_from_ios_device?
  = link_to "Install", install_plist_url(@build), class: "btn btn-primary btn-lg"
  .alert.alert.alert-warning
    Failed to install??
- else
  %p.alert.alert-info Send this URL to your device to install.

app/views/layouts/application.html.haml
%html
  %head
    %title Angled Deck
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': true
    = javascript_include_tag 'application', 'data-turbolinks-track': true
    %meta{ name: "viewport", content: "width=device-width"}
  %body
    - if content_for? :breadcrumb
      %ol.breadcrumb
        = yield :breadcrumb
    .container-fluid
      = yield

app/views/projects/new.html.haml
%h1 New Project
= form_for :project, url: projects_url do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :gh_access_token
    = f.text_field :gh_access_token, class: "form-control"
    %p.help-block The token will be used to comment on pull request from hook.
  = f.submit class: "btn btn-default"

app/views/projects/show.html.haml
%h1= @project.name

.alert.alert-danger
  The URL is private, but this page is not.
  %ul
    %li Make sure bookmark or remember the URL. There is no pointer to this page at all.
    %li Anyone who knows the URL can access this page.

%h2 Topics

= link_to "Add New Topic", new_project_topic_url(@project.guid), class: "btn btn-default"

- @project.topics.order(updated_at: :desc).each do |topic|
  .topic
    %h3= link_to topic_name(topic), project_topic_url(project_id: @project.guid, id: topic.id)
    .updated-at
      Last updated #{local_time_ago(topic.updated_at)}

app/views/topics/new.html.haml
%h1
  Add New Topic
  %small on #{@project.name}

= form_for :topic, url: project_topics_url do |t|
  .form-group
    = t.label :name
    = t.text_field :name, class: "form-control"
  .form-group
    = t.label :url
    = t.text_field :url, class: "form-control"
  = t.submit class: "btn btn-default"

app/views/topics/show.html.haml
- content_for :breadcrumb do
  %li= link_to @project.name, project_url(@project.guid)
  %li.active= topic_name(@topic)

%h1
  = topic_name(@topic)
  %small in #{@project.name}

- if @topic.url
  = link_to @topic.url, @topic.url, target: "_blank"
- else
  There is no associated URL for this topic.

%h2 Builds

= link_to "Add New Build", new_project_topic_build_url(@project.guid, @topic.id), class: "btn btn-default"

- @topic.builds.order(created_at: :desc).each do |build|
  .topic
    %h3= link_to build.name, project_topic_build_url(@project.guid, @topic.id, build.id)
    %div Published #{local_time_ago build.created_at}
    - if request_from_ios_device?
      = link_to "Install", install_plist_url(build), class: "btn btn-primary"

app/views/welcome/index.html.haml
.container-fluid
  %h1 Start New Project
  = link_to "New Project", new_project_url, class: "btn btn-primary"